per character respec
Deevian/pathfinder-kingmaker-respec pull request #13
Opened 2018-10-03 11:51 UTC by akalajzi

It reads the first file, and adds selectable list of characters as a next step. I tested it and it worked well. 

Couple of notes for the PR:
- added .editorconfig as it was impossible to keep the style rules without it (we treat our code very differently :D )
- added rollup-plugin-serve to easily test locally
- I did notice you annotated types, but its not enforced by anything. You're using some IDE/editor to enforce types?
- there are some good opportunities for refactor, but I figured people would want working version as soon as possible.

2018-10-03 13:31 UTC, Deevian requested changes
Heya! Thanks a ton for the PR! I've made a couple of comments (and I apologize if they're too many, old habits die hard) to improve structure, consistency and to avoid having to read the save file twice.

* About the `.editorconfig`, I'll push a linter configuration later today, maybe even with prettier, which should take care of code style.
* Cool stuff with the serve!
* I use WebStorm, which automatically fills JSDoc annotations. It's a cool thing to have, and would be cool if you added them.
* I've commented on some of them -- it's cool to push things fast, and I agree with you there, but we might end up with something unmaintainable if we do too much, too fast.

2018-10-03 13:31 UTC, Deevian commented on .editorconfig
> +[*]
I'd say we dump this for now and enforce a lint configuration later on,

2018-10-03 13:31 UTC, Deevian commented on rollup.config.js
> +        serve(),
I assume this runs an HTTP server that reloads the page whenever you update something? What port does it run on?

2018-10-03 13:31 UTC, Deevian commented on src/helpers.js
> +    if (descriptor.CustomName.length) {
I think we can safely omit `.length` here.

2018-10-03 13:31 UTC, Deevian commented on src/helpers.js
> +export function getCharacterName(descriptor) {
Annotations are simple JSDoc. Some IDE's do that for you almost automatically (i.e. WebStorm), and I imagine text editors will have plugins that fill most stuff automatically by inserting /** and pressing enter. It'd be cool if you could add these to these methods as well! `param` and `returns` annotations will suffice.

See here: http://usejsdoc.org/

2018-10-03 13:31 UTC, Deevian commented on src/helpers.js
> +        return descriptor.CustomName
Please terminate lines with semi-colons (applies to the rest of the review)

2018-10-03 13:31 UTC, Deevian commented on src/helpers.js
> +export function getLoadingEl() {
These make me feel dirty :p

But it's OK for now! I'll try to move this to something like React sometime today.

2018-10-03 13:31 UTC, Deevian commented on index.html
> +                            <li id="loading" class="loading" style="display: none">loading party list...</li>
I'd say skip the `id` here.

2018-10-03 13:31 UTC, Deevian commented on src/helpers.js
> +export function removeLoadingEl() {
Instead of removing it, we could instead set the `display` back to `none`. That would avoid having to check if the element exists or not.

2018-10-03 13:31 UTC, Deevian commented on src/helpers.js
> +    const wrapper = document.getElementsByClassName("party-list")[0]
If we do keep the loader hidden, we should add a `span` or a `div` inside the `li` to place this in without overriding the loader.

2018-10-03 13:31 UTC, Deevian commented on src/index.js
> +window.party = {}
You can just define this as `const party = {};` in the scope of this file, and that'll work fine.

2018-10-03 13:31 UTC, Deevian commented on src/helpers.js
> +        wrapper.innerHTML += `<li id="${id}" class="${className}" onclick="toggleSelection('${id}')">${character.name}</li>`
Having checkboxes in these would avoid having to implement toggling logic.

2018-10-03 13:31 UTC, Deevian commented on src/helpers.js
> +export function toggleSelectedElById(id) {
Related to comment immediately above.

2018-10-03 13:31 UTC, Deevian commented on src/index.js
> +window.toggleSelection = (id) => {
Also related to above comments (i.e., can be avoided by using checkboxes)

2018-10-03 13:31 UTC, Deevian commented on src/index.js
> +    const reader = new JSZip();
Right, so about this -- we're having to read and unpack the save file twice now (i.e. here and in the `readAndDownloadFirstSave`), which seems unecessary.

Instead, why not store the result of this:

`    reader.loadAsync(file)
    .then(() => {
        return Promise.all([
            reader.file("header.json").async("string"),
            reader.file("party.json").async("string"),
        ]);
    })
`

Somewhere, and make use of the already resolved values?

2018-10-03 13:31 UTC, Deevian commented on src/index.js
> +window.party = {}
Ah, we could also avoid having this entirely. In `readAndDownloadFirstSave` (with some other new name) we could simply check which checkboxes were selected at a given time, and make use of that,

2018-10-03 13:31 UTC, Deevian commented on src/consts.js
> +export default characterNames;
Okay, so here, either name the file as `characterNameMap` or `characterNameEnum`, or return `{ characterNames }`. Having a `consts` file that returns the character name map by default is confusing.

2018-10-03 13:31 UTC, Deevian commented on src/index.js
> +const injectPartyList = (usedParty) => {
Sanity check here -- it's not clear why some stuff is in the utils and why other stuff is in the main file.

2018-10-03 13:31 UTC, Deevian commented on src/index.js
> +    .then(() => {
Any reason to remove the indentation?

2018-10-03 13:31 UTC, Deevian commented on src/index.js
> +            if (party[descriptor.Blueprint].shouldRespec) {
> (...) if checkbox for with blueprint class is selected, set `Recreate` as true (...)

2018-10-03 13:31 UTC, Deevian commented on src/index.js
> +    .then(() => {
Again, you removed the indentation here :p

2018-10-03 13:35 UTC, akalajzi commented on rollup.config.js
> +        serve(),
Yup, super simple serving, on 10001 if I'm not mistaken as a default. It notifies you from the console where its serving.

2018-10-03 13:36 UTC, akalajzi commented on src/helpers.js
> +    if (descriptor.CustomName.length) {
No, default is empty string, which would return true.

2018-10-03 13:37 UTC, Deevian commented on src/helpers.js
> +    if (descriptor.CustomName.length) {
Oh, damn, you're right, my bad!

2018-10-03 13:37 UTC, akalajzi commented on src/helpers.js
> +        return descriptor.CustomName
I'd need to enforce this with some config, as its impossible to track it :D

2018-10-03 13:37 UTC, Deevian commented on rollup.config.js
> +        serve(),
Nice! :+1:

2018-10-03 13:37 UTC, Deevian commented on src/helpers.js
> +        return descriptor.CustomName
Yup, makes total sense. I'll approve the PR without this change, and will push the linter later on (which should fix it).

2018-10-03 13:38 UTC, akalajzi commented on src/consts.js
> +export default characterNames;
Perhaps, initially had idea for some other consts being served from the same file. Ended up with only names, so exported it as default.

2018-10-03 13:39 UTC, akalajzi commented on src/index.js
> +    .then(() => {
Auto indented via editor.

2018-10-03 13:41 UTC, Deevian commented on src/index.js
> +    .then(() => {
I guess it will be fixed with linter :+1:

2018-10-03 13:43 UTC, akalajzi commented on src/helpers.js
> +export function getLoadingEl() {
Nothing really dirty there; its the way to deal with DOM without some library. TBH, everything would be a lot easier with React, but it seemed silly to add it for such a trivial use case.

2018-10-03 13:46 UTC, Deevian commented on src/helpers.js
> +export function getLoadingEl() {
Yup, I know, that's just me spending too much time without messing directly with the DOM. It might be silly right now, sure, but we move on to allowing some other changes, it starts to make more sense in a long-term perspective.

Maybe even something like choo (https://github.com/choojs/choo) would help :p

2018-10-03 13:51 UTC, akalajzi commented on index.html
> +                            <li id="loading" class="loading" style="display: none">loading party list...</li>
Selecting with css class (that indeed is a styling class, not a selector class) is a bad practice. Eventually you'll place a loader on a second step or something, and this will break.

2018-10-03 13:55 UTC, Deevian commented on index.html
> +                            <li id="loading" class="loading" style="display: none">loading party list...</li>
Sure, I'd say add a `class` that is only used to select the element here instead of the `id`. In general, and the `label` element and `for` attribute notwithstanding, I'd say avoid using `id`s since they'll pollute the global namespace and might result in errors if we need loaders elsewhere.

2018-10-03 14:12 UTC, akalajzi commented
Started typing and then noticed the sheer amount of issues :joy:  
Look, it's a late night work that indeed works. While I agree with you that there's nicer or more performant ways to do something, it seems really pointless, unless you're moving this in some bigger direction that'll allow you to fine tune your saves. I mean, the current state of the project isnt really the definition of clean and pretty. I'm not going to install editor plugin that will allow me to place annotations for documentation that'll never be generated. Or worry about performance of reading the file twice in a page that sits and does nothing for quite a lot of time that is needed to finish the whole process. Or rewrite implementation to checkboxes, for... not sure why exactly. I actually had "Everyone" as one of the option that gets set/reset depending on other clicks, but removed it because I couldnt spare enough time to finish it. Considering you'd like to introduce a library of some sorts you'd rewrite most of UI handling anyway.  
I understand that you'd like to do it "right", but I dont share the drive to do so. So no hard feelings, but this is now as-is. Merge and rework before building new version, or just reject and copy parts that'll help you. I just wanted to respec two characters, and this work allowed me to do so :)

2018-10-03 14:19 UTC, Deevian commented
Sure thing @akalajzi , no hard feelings at all, and I really do appreciate the effort you've put into this. I would indeed like to do it right, and while at the moment what I have it isn't quite the definition of it, I'd like to strive towards something that's closer to it.

I'll pick the up the PR where you've left off and will try to merge it later today.

2018-10-03 14:35 UTC, akalajzi commented
Sure thing. Good luck, I'll continue to follow the project. :+1:

2018-10-05 19:33 UTC, Deevian commented
Implemented in 31badfb0996ff8f03d19e26a4b18f9f77b095a7f

2018-10-05 19:33 UTC, closed without merging